server:
  port: 30000
  servlet:
    session:
      timeout: 120
      cookie:
        path: /
    context-path: /rest

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/supplychain?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/mariadb/*Mapper.xml
  type-aliases-package: com.bokyeefung.webtools.webtoolsmainservice.common.dao.mapper
